// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsCoreFetch.Migrations
{
    [DbContext(typeof(BanksListenerContext))]
    partial class BanksListenerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("ConsCoreFetch.Domain.KomBankRatesLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bank")
                        .HasColumnType("TEXT");

                    b.Property<double>("EurA")
                        .HasColumnType("REAL");

                    b.Property<double>("EurB")
                        .HasColumnType("REAL");

                    b.Property<double>("EurUsdA")
                        .HasColumnType("REAL");

                    b.Property<double>("EurUsdB")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("LastCheck")
                        .HasColumnType("TEXT");

                    b.Property<double>("RubA")
                        .HasColumnType("REAL");

                    b.Property<double>("RubB")
                        .HasColumnType("REAL");

                    b.Property<double>("RubEurA")
                        .HasColumnType("REAL");

                    b.Property<double>("RubEurB")
                        .HasColumnType("REAL");

                    b.Property<double>("RubUsdA")
                        .HasColumnType("REAL");

                    b.Property<double>("RubUsdB")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("StartedFrom")
                        .HasColumnType("TEXT");

                    b.Property<double>("UsdA")
                        .HasColumnType("REAL");

                    b.Property<double>("UsdB")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("KomBankRates");
                });
#pragma warning restore 612, 618
        }
    }
}
