<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>12</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Playwright" Version="1.55.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BalisStandard\BalisStandard.csproj" />
  </ItemGroup>

</Project>
